### ISSUE TITLE
Utiliza cadenas

### ISSUE THREAD

**Issue by semurat** [LVerus/StringCalculator#1]
Queda mas legible si pones la cadena que vas a probar. Seguramente pensaste en sacar lo a propiedades de la clase para reutilzarlas pero en este caso dentro del test queda mas claro si vemso el input directamente no con toString() y concatenacion de cadenas.

https://github.com/LVerus/StringCalculator/blob/bff40f9af5c87e705c3b619b1621b1fdf189ce87/StringCalculator/src/test/java/com/LVerus/ejemplos/TestStringCalculator.java#L35

**Comment by LVerus** [comment]
La verdad es que lo hice con mis hijas detrás de mí pegando botes por el salón y cuando lo pensé tenía mejor pinta, ahora mismo tiene una pinta horrible. 

Gracias por el comentario.

**Comment by semurat** [comment]
No pasa nada, es el tipico codigo que vas escribiendo y segun lo haces te sirve...por eso luego es bueno hacer el refactor, o incluso al dia sigueinte cuando lo vuelves a ver y te planteas si lo puedes dejar algo mas limpio.
