### ISSUE TITLE
Nombre de los metodos de test

### ISSUE THREAD

**Issue by semurat** [LVerus/StringCalculator#2]
Es una buena practica en lso nombres de los metodos explicar lo que hace y lo que espera obtener, de manera que cuando revisemos los reports que podamos genera en la ejecucion podamos leerlos y entender, alguien ajeno o nuevo al proyecto, que es lo que estamos probando en ese punto.

https://github.com/LVerus/StringCalculator/blob/bff40f9af5c87e705c3b619b1621b1fdf189ce87/StringCalculator/src/test/java/com/LVerus/ejemplos/TestStringCalculator.java#L22

**Comment by LVerus** [comment]
Sí, la verdad es que a veces es dificil poner nombre más claros porque como lo estás haciendo tú lo entiende a la perfección :-)

**Comment by semurat** [comment]
No te preocupes...aun a dia de hoy os podria enseñar algun test mio que implemento y que luego a los dos dias no se lo que esta probando... asi que es normal
